// Mock data for the AI Smart Wardrobe application

export interface WardrobeItem {
  id: string;
  name: string;
  category: string;
  subCategory: string;
  primaryColor: string;
  colors: string[];
  season: string[];
  occasions: string[];
  style: string[];
  material?: string;
  pattern?: string;
  brand?: string;
  description?: string;
  status: 'available' | 'washing' | 'lent' | 'pending_review';
  wearCount: number;
  lastWorn?: string;
  imageUrl: string;
  confidence?: number;
}

export interface Outfit {
  id: string;
  name: string;
  items: WardrobeItem[];
  occasion: string;
  style: string;
  season: string;
  source: 'ai_text' | 'ai_reference' | 'manual';
  createdAt: string;
  lastWorn?: string;
  explanation?: string;
  weather?: string;
}

export interface WearLog {
  id: string;
  date: string;
  outfitId?: string;
  items: string[];
  weather: string;
  feedback?: string;
  occasion: string;
}

export interface UserProfile {
  name: string;
  avatar: string;
  city: string;
  wardrobeDays: number;
  totalItems: number;
  totalOutfits: number;
  stylePreferences: string[];
  colorPreferences: string[];
  avoidItems: string[];
}

export const wardrobeItems: WardrobeItem[] = [
  {
    id: 'item-001',
    name: '白色纯棉衬衫',
    category: '上装',
    subCategory: '衬衫',
    primaryColor: '#FFFFFF',
    colors: ['白色'],
    season: ['春夏'],
    occasions: ['日常', '通勤', '休闲'],
    style: ['简约', '基础'],
    material: '纯棉',
    pattern: '纯色',
    description: '经典白色翻领衬衫，纯棉面料透气舒适，修身剪裁，适合通勤和日常穿着，可单穿或作为内搭',
    status: 'available',
    wearCount: 23,
    lastWorn: '2026-07-22',
    imageUrl: '/clothing/white-shirt.jpeg',
    confidence: 0.98,
  },
  {
    id: 'item-002',
    name: '深蓝修身西裤',
    category: '下装',
    subCategory: '长裤',
    primaryColor: '#1B3A5C',
    colors: ['深蓝'],
    season: ['春秋', '秋冬'],
    occasions: ['日常', '通勤', '商务'],
    style: ['休闲', '经典'],
    material: '羊毛混纺',
    pattern: '纯色',
    description: '深蓝色修身直筒西裤，羊毛混纺面料垂感好，中腰设计，适合商务通勤和正式场合',
    status: 'available',
    wearCount: 18,
    lastWorn: '2026-07-21',
    imageUrl: '/clothing/navy-trousers.jpeg',
    confidence: 0.96,
  },
  {
    id: 'item-003',
    name: '驼色羊毛西装',
    category: '外套',
    subCategory: '西装',
    primaryColor: '#C4A47A',
    colors: ['驼色'],
    season: ['春秋'],
    occasions: ['商务', '正式', '通勤'],
    style: ['正式', '干练'],
    material: '羊毛混纺',
    pattern: '纯色',
    brand: 'ZARA',
    description: '驼色单粒扣西装外套，羊毛混纺面料保暖挺括，经典翻领设计，适合商务会议和正式场合',
    status: 'available',
    wearCount: 12,
    lastWorn: '2026-07-18',
    imageUrl: '/clothing/camel-blazer.jpeg',
    confidence: 0.95,
  },
  {
    id: 'item-004',
    name: '灰色美利奴毛衣',
    category: '上装',
    subCategory: '针织',
    primaryColor: '#A0A0A0',
    colors: ['灰色'],
    season: ['春秋', '秋冬'],
    occasions: ['日常', '通勤', '约会'],
    style: ['温柔', '简约'],
    material: '美利奴羊毛',
    pattern: '纯色',
    description: '灰色圆领套头毛衣，美利奴羊毛柔软亲肤，中等厚度适合叠穿，温柔简约风格',
    status: 'available',
    wearCount: 8,
    lastWorn: '2026-07-15',
    imageUrl: '/clothing/gray-sweater.jpeg',
    confidence: 0.92,
  },
  {
    id: 'item-005',
    name: '橄榄绿工装裤',
    category: '下装',
    subCategory: '长裤',
    primaryColor: '#5A6B4A',
    colors: ['橄榄绿'],
    season: ['春秋', '夏'],
    occasions: ['日常', '休闲'],
    style: ['休闲', '工装'],
    material: '棉',
    pattern: '纯色',
    description: '橄榄绿直筒工装裤，纯棉面料耐磨舒适，多口袋设计，休闲工装风格，适合日常出行',
    status: 'available',
    wearCount: 15,
    lastWorn: '2026-07-20',
    imageUrl: '/clothing/olive-cargo.jpeg',
    confidence: 0.94,
  },
  {
    id: 'item-006',
    name: '黑色皮质斜挎包',
    category: '包',
    subCategory: '斜挎包',
    primaryColor: '#2C2C2C',
    colors: ['黑色'],
    season: ['四季'],
    occasions: ['通勤', '商务', '日常'],
    style: ['经典', '干练'],
    material: '真皮',
    brand: 'COACH',
    description: '黑色真皮斜挎包，COACH品牌，可调节肩带，容量适中，适合通勤和商务场合',
    status: 'available',
    wearCount: 30,
    lastWorn: '2026-07-23',
    imageUrl: '/clothing/black-crossbody-bag.jpeg',
    confidence: 0.97,
  },
  {
    id: 'item-007',
    name: '白色极简运动鞋',
    category: '鞋',
    subCategory: '运动鞋',
    primaryColor: '#F8F8F8',
    colors: ['白色'],
    season: ['春夏秋'],
    occasions: ['日常', '休闲', '通勤'],
    style: ['休闲', '简约'],
    material: '皮革',
    pattern: '纯色',
    description: '白色皮革运动鞋，极简设计无logo，厚底舒适，百搭休闲，适合日常通勤和周末出行',
    status: 'available',
    wearCount: 25,
    lastWorn: '2026-07-22',
    imageUrl: '/clothing/white-sneakers.jpeg',
    confidence: 0.93,
  },
  {
    id: 'item-008',
    name: '蓝白条纹T恤',
    category: '上装',
    subCategory: 'T恤',
    primaryColor: '#4A6FA5',
    colors: ['蓝色', '白色'],
    season: ['春夏'],
    occasions: ['日常', '休闲', '通勤'],
    style: ['法式', '简约'],
    material: '棉',
    pattern: '条纹',
    description: '蓝白横条纹圆领T恤，纯棉面料透气，法式休闲风格，适合春夏季节日常穿着',
    status: 'available',
    wearCount: 10,
    lastWorn: '2026-07-17',
    imageUrl: '/clothing/striped-tee.jpeg',
    confidence: 0.91,
  },
  {
    id: 'item-009',
    name: '酒红色丝巾',
    category: '配饰',
    subCategory: '丝巾',
    primaryColor: '#722F37',
    colors: ['酒红'],
    season: ['春秋'],
    occasions: ['约会', '通勤', '聚会'],
    style: ['优雅', '精致'],
    material: '真丝',
    pattern: '印花',
    description: '酒红色真丝方巾，精致印花图案，可系颈间或包饰，提升整体造型精致度',
    status: 'available',
    wearCount: 5,
    lastWorn: '2026-07-10',
    imageUrl: '/clothing/burgundy-scarf.jpeg',
    confidence: 0.89,
  },
  {
    id: 'item-010',
    name: '棕色牛津鞋',
    category: '鞋',
    subCategory: '皮鞋',
    primaryColor: '#8B5E3C',
    colors: ['棕色'],
    season: ['春秋', '秋冬'],
    occasions: ['通勤', '商务', '正式'],
    style: ['经典', '绅士'],
    material: '真皮',
    pattern: '纯色',
    description: '棕色真皮牛津鞋，经典系带设计，适合商务正装和正式场合，搭配西裤效果佳',
    status: 'available',
    wearCount: 20,
    lastWorn: '2026-07-21',
    imageUrl: '/clothing/brown-oxfords.jpeg',
    confidence: 0.96,
  },
  {
    id: 'item-011',
    name: '浅蓝牛仔夹克',
    category: '外套',
    subCategory: '夹克',
    primaryColor: '#6B9AC4',
    colors: ['浅蓝'],
    season: ['春秋'],
    occasions: ['日常', '休闲'],
    style: ['休闲', '复古'],
    material: '牛仔',
    pattern: '纯色',
    description: '浅蓝色水洗牛仔夹克，经典翻领纽扣设计，休闲复古风格，适合叠穿增加层次感',
    status: 'available',
    wearCount: 7,
    lastWorn: '2026-07-12',
    imageUrl: '/clothing/denim-jacket.jpeg',
    confidence: 0.94,
  },
  {
    id: 'item-012',
    name: '黑色高领毛衣',
    category: '上装',
    subCategory: '针织',
    primaryColor: '#1A1A1A',
    colors: ['黑色'],
    season: ['秋冬'],
    occasions: ['通勤', '约会', '正式'],
    style: ['简约', '优雅'],
    material: '羊绒',
    pattern: '纯色',
    description: '黑色羊绒高领毛衣，柔软亲肤保暖，简约优雅，秋冬季节内搭或单穿均可',
    status: 'available',
    wearCount: 9,
    lastWorn: '2026-07-16',
    imageUrl: '/clothing/black-turtleneck.jpeg',
    confidence: 0.95,
  },
  {
    id: 'item-013',
    name: '白色阔腿亚麻裤',
    category: '下装',
    subCategory: '长裤',
    primaryColor: '#F0EDE5',
    colors: ['白色', '米白'],
    season: ['春夏'],
    occasions: ['日常', '休闲', '度假'],
    style: ['简约', '清爽'],
    material: '亚麻',
    pattern: '纯色',
    description: '米白色高腰阔腿亚麻裤，透气凉爽，垂坠感好，春夏季节清爽舒适的百搭单品',
    status: 'available',
    wearCount: 6,
    lastWorn: '2026-07-14',
    imageUrl: '/clothing/white-linen-pants.jpeg',
    confidence: 0.93,
  },
  {
    id: 'item-014',
    name: '炭灰色羊毛大衣',
    category: '外套',
    subCategory: '大衣',
    primaryColor: '#4A4A4A',
    colors: ['灰色'],
    season: ['秋冬'],
    occasions: ['通勤', '正式', '商务'],
    style: ['经典', '大气'],
    material: '羊毛',
    pattern: '纯色',
    description: '炭灰色长款羊毛大衣，双排扣设计，版型挺括大气，秋冬季节通勤和正式场合的首选外套',
    status: 'available',
    wearCount: 11,
    lastWorn: '2026-07-08',
    imageUrl: '/clothing/charcoal-overcoat.jpeg',
    confidence: 0.96,
  },
  // 新增衣物 - 扩展衣橱多样性
  {
    id: 'item-015',
    name: '米色高领毛衣',
    category: '上装',
    subCategory: '针织衫',
    primaryColor: '#E8DCC8',
    colors: ['米色', '杏色'],
    season: ['秋冬'],
    occasions: ['日常', '通勤', '约会'],
    style: ['优雅', '简约'],
    material: '羊绒混纺',
    pattern: '纯色',
    status: 'available',
    wearCount: 12,
    lastWorn: '2026-07-10',
    confidence: 0.95,
    description: '柔软米色羊绒高领毛衣，细腻针织纹理，修身剪裁展现优雅气质，适合秋冬叠穿或单穿',
    imageUrl: '/clothing/beige-sweater.jpeg',
  },
  {
    id: 'item-016',
    name: '黑色皮夹克',
    category: '外套',
    subCategory: '夹克',
    primaryColor: '#1A1A1A',
    colors: ['黑色'],
    season: ['春秋'],
    occasions: ['日常', '休闲', '约会'],
    style: ['街头', '酷感'],
    material: '真皮',
    pattern: '纯色',
    status: 'available',
    wearCount: 18,
    lastWorn: '2026-07-15',
    confidence: 0.97,
    description: '经典黑色真皮机车夹克，银色拉链点缀，修身版型利落有型，增添酷感与个性',
    imageUrl: '/clothing/black-leather-jacket.jpeg',
  },
  {
    id: 'item-017',
    name: '酒红色针织连衣裙',
    category: '连衣裙',
    subCategory: '针织裙',
    primaryColor: '#722F37',
    colors: ['酒红', '深红'],
    season: ['秋冬'],
    occasions: ['通勤', '约会', '商务'],
    style: ['优雅', '知性'],
    material: '羊毛混纺',
    pattern: '纯色',
    status: 'available',
    wearCount: 8,
    lastWorn: '2026-07-08',
    confidence: 0.94,
    description: '酒红色修身针织连衣裙，及膝长度优雅得体，柔软羊毛混纺面料，展现知性女性魅力',
    imageUrl: '/clothing/burgundy-knit-dress.jpeg',
  },
  {
    id: 'item-018',
    name: '卡其色工装裤',
    category: '下装',
    subCategory: '长裤',
    primaryColor: '#C3B091',
    colors: ['卡其', '米棕'],
    season: ['春夏秋'],
    occasions: ['日常', '休闲', '户外'],
    style: ['休闲', '工装'],
    material: '棉质',
    pattern: '纯色',
    status: 'available',
    wearCount: 22,
    lastWorn: '2026-07-18',
    confidence: 0.96,
    description: '卡其色直筒工装裤，多口袋设计实用时尚，纯棉面料舒适透气，百搭休闲风格',
    imageUrl: '/clothing/khaki-cargo-pants.jpeg',
  },
  {
    id: 'item-019',
    name: '浅蓝色牛仔衬衫',
    category: '上装',
    subCategory: '衬衫',
    primaryColor: '#A4C8E0',
    colors: ['浅蓝', '牛仔蓝'],
    season: ['春夏秋'],
    occasions: ['日常', '休闲', '通勤'],
    style: ['休闲', '简约'],
    material: '牛仔棉',
    pattern: '纯色',
    status: 'available',
    wearCount: 15,
    lastWorn: '2026-07-12',
    confidence: 0.95,
    description: '浅蓝色水洗牛仔衬衫，柔软舒适不僵硬，可单穿或作为外套叠穿，休闲百搭',
    imageUrl: '/clothing/light-blue-denim-shirt.jpeg',
  },
  {
    id: 'item-020',
    name: '灰色格纹西装',
    category: '外套',
    subCategory: '西装',
    primaryColor: '#8B8B8B',
    colors: ['灰色', '格纹'],
    season: ['春秋'],
    occasions: ['通勤', '商务', '正式'],
    style: ['商务', '经典'],
    material: '羊毛混纺',
    pattern: '格纹',
    status: 'available',
    wearCount: 10,
    lastWorn: '2026-07-05',
    confidence: 0.96,
    description: '灰色细格纹羊毛西装，经典商务版型，修身剪裁展现专业形象，适合正式场合',
    imageUrl: '/clothing/grey-plaid-blazer.jpeg',
  },
  {
    id: 'item-021',
    name: '白色帆布鞋',
    category: '鞋',
    subCategory: '休闲鞋',
    primaryColor: '#FFFFFF',
    colors: ['白色'],
    season: ['春夏秋'],
    occasions: ['日常', '休闲', '运动'],
    style: ['休闲', '简约'],
    material: '帆布',
    pattern: '纯色',
    status: 'available',
    wearCount: 35,
    lastWorn: '2026-07-20',
    confidence: 0.98,
    description: '经典白色低帮帆布鞋，橡胶底耐磨防滑，简洁百搭，日常休闲必备单品',
    imageUrl: '/clothing/white-canvas-shoes.jpeg',
  },
  {
    id: 'item-022',
    name: '黑色斜挎包',
    category: '包',
    subCategory: '斜挎包',
    primaryColor: '#1A1A1A',
    colors: ['黑色'],
    season: ['四季'],
    occasions: ['日常', '通勤', '休闲'],
    style: ['简约', '实用'],
    material: '尼龙',
    pattern: '纯色',
    status: 'available',
    wearCount: 28,
    lastWorn: '2026-07-19',
    confidence: 0.97,
    description: '黑色尼龙斜挎包，轻便防水多隔层，可调节肩带，实用百搭日常必备',
    imageUrl: '/clothing/black-crossbody-bag.jpeg',
  },
  {
    id: 'item-023',
    name: '墨绿色丝巾',
    category: '配饰',
    subCategory: '丝巾',
    primaryColor: '#2F4F4F',
    colors: ['墨绿', '深绿'],
    season: ['春夏秋'],
    occasions: ['通勤', '约会', '正式'],
    style: ['优雅', '精致'],
    material: '真丝',
    pattern: '印花',
    status: 'available',
    wearCount: 6,
    lastWorn: '2026-07-02',
    confidence: 0.93,
    description: '墨绿色真丝方巾，精致印花图案，可系颈间或装饰包袋，增添优雅细节',
    imageUrl: '/clothing/dark-green-silk-scarf.jpeg',
  },
  {
    id: 'item-024',
    name: '深蓝色连帽卫衣',
    category: '上装',
    subCategory: '卫衣',
    primaryColor: '#1B3A5C',
    colors: ['深蓝', '藏青'],
    season: ['春夏秋'],
    occasions: ['日常', '休闲', '运动'],
    style: ['休闲', '运动'],
    material: '纯棉',
    pattern: '纯色',
    status: 'available',
    wearCount: 20,
    lastWorn: '2026-07-16',
    confidence: 0.96,
    description: '深蓝色纯棉连帽卫衣，柔软舒适透气，前口袋设计实用，休闲运动风格',
    imageUrl: '/clothing/navy-hoodie.jpeg',
  },
  {
    id: 'item-025',
    name: '米白色阔腿裤',
    category: '下装',
    subCategory: '长裤',
    primaryColor: '#F5F5DC',
    colors: ['米白', '本白'],
    season: ['春夏'],
    occasions: ['日常', '通勤', '休闲'],
    style: ['优雅', '简约'],
    material: '棉麻混纺',
    pattern: '纯色',
    status: 'available',
    wearCount: 14,
    lastWorn: '2026-07-14',
    confidence: 0.95,
    description: '米白色高腰阔腿裤，棉麻混纺透气舒适，垂坠感好，展现优雅气质',
    imageUrl: '/clothing/cream-wide-leg-pants.jpeg',
  },
  {
    id: 'item-026',
    name: '棕色切尔西靴',
    category: '鞋',
    subCategory: '靴子',
    primaryColor: '#8B4513',
    colors: ['棕色', '深棕'],
    season: ['秋冬'],
    occasions: ['日常', '通勤', '休闲'],
    style: ['经典', '复古'],
    material: '真皮',
    pattern: '纯色',
    status: 'available',
    wearCount: 16,
    lastWorn: '2026-07-09',
    confidence: 0.96,
    description: '棕色真皮切尔西靴，经典圆头设计，弹性侧边方便穿脱，百搭秋冬必备',
    imageUrl: '/clothing/brown-chelsea-boots.jpeg',
  },
];

export const outfits: Outfit[] = [
  {
    id: 'outfit-001',
    name: '商务休闲通勤',
    items: [wardrobeItems[2], wardrobeItems[0], wardrobeItems[1], wardrobeItems[5], wardrobeItems[9]],
    occasion: '通勤',
    style: '商务休闲',
    season: '春秋',
    source: 'ai_text',
    createdAt: '2026-07-22',
    lastWorn: '2026-07-22',
    explanation: '驼色西装搭配白衬衫和深蓝西裤，正式但不刻板，棕色牛津鞋增添质感',
    weather: '18-24°C 多云',
  },
  {
    id: 'outfit-002',
    name: '周末休闲出行',
    items: [wardrobeItems[7], wardrobeItems[4], wardrobeItems[6]],
    occasion: '日常',
    style: '休闲',
    season: '春夏',
    source: 'ai_text',
    createdAt: '2026-07-20',
    lastWorn: '2026-07-20',
    explanation: '蓝白条纹T恤搭配橄榄绿工装裤和白色运动鞋，轻松舒适的周末穿搭',
    weather: '24-30°C 晴',
  },
  {
    id: 'outfit-003',
    name: '优雅精致装扮',
    items: [wardrobeItems[11], wardrobeItems[12], wardrobeItems[8], wardrobeItems[5]],
    occasion: '约会',
    style: '优雅',
    season: '春秋',
    source: 'ai_reference',
    createdAt: '2026-07-18',
    explanation: '黑色高领毛衣搭配白色阔腿裤，酒红丝巾点缀，优雅大方',
    weather: '16-22°C 晴',
  },
  {
    id: 'outfit-004',
    name: '春秋层次感穿搭',
    items: [wardrobeItems[10], wardrobeItems[3], wardrobeItems[1], wardrobeItems[9]],
    occasion: '通勤',
    style: '经典',
    season: '春秋',
    source: 'manual',
    createdAt: '2026-07-15',
    lastWorn: '2026-07-17',
    explanation: '牛仔夹克内搭灰色毛衣，层次分明又保暖，牛津鞋提升正式感',
    weather: '14-20°C 阴',
  },
];

export const wearLogs: WearLog[] = [
  { id: 'log-001', date: '2026-07-23', outfitId: 'outfit-001', items: ['item-006'], weather: '26°C 晴', feedback: '刚好', occasion: '通勤' },
  { id: 'log-002', date: '2026-07-22', outfitId: 'outfit-001', items: ['item-001', 'item-007'], weather: '24°C 多云', feedback: '刚好', occasion: '通勤' },
  { id: 'log-003', date: '2026-07-21', items: ['item-002', 'item-010'], weather: '22°C 阴', occasion: '日常' },
  { id: 'log-004', date: '2026-07-20', outfitId: 'outfit-002', items: ['item-004', 'item-005', 'item-007'], weather: '28°C 晴', feedback: '太热', occasion: '休闲' },
  { id: 'log-005', date: '2026-07-18', items: ['item-003'], weather: '20°C 多云', occasion: '商务' },
  { id: 'log-006', date: '2026-07-17', outfitId: 'outfit-004', items: ['item-011', 'item-008'], weather: '18°C 阴', feedback: '刚好', occasion: '通勤' },
  { id: 'log-007', date: '2026-07-16', items: ['item-012'], weather: '25°C 晴', occasion: '聚会' },
  { id: 'log-008', date: '2026-07-15', items: ['item-004'], weather: '22°C 晴', occasion: '日常' },
];

export const userProfile: UserProfile = {
  name: '小明',
  avatar: '',
  city: '上海',
  wardrobeDays: 45,
  totalItems: 86,
  totalOutfits: 24,
  stylePreferences: ['简约', '商务休闲', '经典'],
  colorPreferences: ['黑色', '白色', '深蓝', '灰色'],
  avoidItems: ['荧光色', '大面积印花'],
};

// AI styling scenarios - using lucide icon names
export const quickScenarios = [
  { label: '通勤上班', icon: 'Briefcase' },
  { label: '约会聚餐', icon: 'Wine' },
  { label: '周末出游', icon: 'Sun' },
  { label: '商务会议', icon: 'ClipboardList' },
];

// Categories for wardrobe filter
export const categories = [
  { label: '全部', value: 'all' },
  { label: '上装', value: '上装' },
  { label: '下装', value: '下装' },
  { label: '连体', value: '连体' },
  { label: '外套', value: '外套' },
  { label: '鞋', value: '鞋' },
  { label: '包', value: '包' },
  { label: '配饰', value: '配饰' },
];

// Calendar events for outfit planning
export interface CalendarEvent {
  id: string;
  date: string;
  type: 'planned' | 'worn';
  outfitId?: string;
  outfit?: Outfit;
  occasion?: string;
  weather?: string;
  feedback?: string;
}

export const calendarEvents: CalendarEvent[] = [
  {
    id: 'cal-001',
    date: '2026-07-28',
    type: 'planned',
    outfitId: 'outfit-001',
    outfit: outfits[0],
    occasion: '通勤',
    weather: '22-28°C 多云',
  },
  {
    id: 'cal-002',
    date: '2026-07-27',
    type: 'worn',
    outfitId: 'outfit-002',
    outfit: outfits[1],
    occasion: '休闲',
    weather: '24-30°C 晴',
    feedback: '刚好',
  },
  {
    id: 'cal-003',
    date: '2026-07-26',
    type: 'worn',
    outfitId: 'outfit-003',
    outfit: outfits[2],
    occasion: '约会',
    weather: '20-26°C 晴',
    feedback: '刚好',
  },
  {
    id: 'cal-004',
    date: '2026-07-25',
    type: 'worn',
    outfitId: 'outfit-001',
    outfit: outfits[0],
    occasion: '通勤',
    weather: '21-27°C 阴',
    feedback: '刚好',
  },
  {
    id: 'cal-005',
    date: '2026-07-30',
    type: 'planned',
    outfitId: 'outfit-004',
    outfit: outfits[3],
    occasion: '通勤',
    weather: '19-25°C 多云',
  },
];

// Weather context
export const weatherContext = {
  city: '上海',
  temperature: 26,
  tempRange: '22-28°C',
  condition: '多云',
  humidity: 65,
  uvIndex: 5,
};

// Today's recommended outfit
export const todayOutfit: Outfit = {
  id: 'today-001',
  name: '今日推荐 · 商务休闲',
  items: [wardrobeItems[0], wardrobeItems[1], wardrobeItems[5], wardrobeItems[9]],
  occasion: '通勤',
  style: '商务休闲',
  season: '春夏',
  source: 'ai_text',
  createdAt: '2026-07-24',
  explanation: '白色衬衫搭配深蓝西裤和棕色牛津鞋，简洁干练，适合今天的商务场合',
  weather: '22-28°C 多云',
};

// Alternative outfits for today
export const todayAlternatives: Outfit[] = [
  todayOutfit,
  {
    id: 'today-002',
    name: '备选方案 · 清爽休闲',
    items: [wardrobeItems[7], wardrobeItems[12], wardrobeItems[6], wardrobeItems[8]],
    occasion: '日常',
    style: '休闲',
    season: '春夏',
    source: 'ai_text',
    createdAt: '2026-07-24',
    explanation: '条纹T恤搭配白色阔腿裤和运动鞋，轻松清爽的夏日穿搭',
    weather: '22-28°C 多云',
  },
  {
    id: 'today-003',
    name: '备选方案 · 层次叠穿',
    items: [wardrobeItems[11], wardrobeItems[1], wardrobeItems[10], wardrobeItems[5]],
    occasion: '通勤',
    style: '经典',
    season: '春秋',
    source: 'ai_text',
    createdAt: '2026-07-24',
    explanation: '黑色高领搭配深蓝西裤和牛仔夹克，层次感强，空调房也不怕冷',
    weather: '22-28°C 多云',
  },
];
